# Package parameters

PKG_NAME = boost

PKG_VERSION = 1.49.0

PKG_COMPRESSED = boost_1_49_0.tar.bz2

PKG_EXTRACT = tar xjf

PKG_PATCHES =


# Special rules for this package

pre-fetch :

post-patch :

build :


pre-install :

# Include common package rules

include ../pkg.common

