#!/bin/bash

if [ "x${HPCP_HOST}" = x ]; then
	echo "You must have the \"HPCP_HOST\" environment variable defined"
	exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# setup environment
if [ -e ${DIR}/system/${HPCP_HOST}.sh ]; then
	. ${DIR}/system/${HPCP_HOST}.sh
fi

# call actual perl program
${DIR}/hpcp_exec.pl "$@"

exit
