  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module swap gcc gcc/6.1.0
    module swap cray-mpich cray-mpich/7.4.1
    module swap cray-shmem cray-shmem/7.4.1
    module load intel
    module load git
  }
  
  setenv CRAYPE_LINK_TYPE dynamic
