  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module unload cray-shmem
    module swap gcc gcc/5.1.0
    module swap craype craype/2.4.2
    module swap cray-mpich cray-mpich/7.2.5
    if [ is-loaded darshan ] {
        module unload darshan
    }
  }
  
  setenv CRAYPE_LINK_TYPE dynamic
