  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module unload cray-shmem
    module swap gcc gcc/5.2.0
    module swap intel intel/15.0.1.133
    module swap craype craype/2.5.0
    module swap cray-mpich cray-mpich/7.3.0
    module load cray-libsci/13.3.0
    module load git/2.4.6
    module load zlib/1.2.7
    module load curl/7.28.1
    module load bzip2/1.0.6
    if [ is-loaded darshan ] {
        module unload darshan
    }
  }
  
  setenv CRAYPE_LINK_TYPE dynamic
  prepend-path CPATH /opt/cray/libsci/13.3.0/GNU/51/sandybridge/include

