  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module unload cray-shmem
    module unload cray-shmem
    module swap craype craype/2.03
    module swap gcc gcc/4.8.2
    module load mkl/13.0.3
    module load git/1.8.1.1
    module load ccm
    if [ "x${loadeddarshan}" != x ]; then
        module unload darshan
    fi
  }
