  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module unload cray-shmem
    module swap gcc gcc/4.8.1
    module swap craype craype/1.06
    module swap cray-mpich cray-mpich/6.0.2
    module load mkl/13.0.1
    module load git/1.8.1.1
    module load python/2.7.3
    module load zlib/1.2.7
    module load curl/7.28.1
    module load cmake/2.8.10.2
    module load bzip2/1.0.6
    if [ is-loaded darshan ] {
        module unload darshan
    }
    module load darshan/2.2.7-106
  }
