  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module swap gcc gcc/5.2.0
    module load intel/15.0.1.133
    module load git/2.4.6
    module load zlib/1.2.7
    module load curl/7.28.1
    module load bzip2/1.0.6
  }
  
  setenv CRAYPE_LINK_TYPE dynamic
