  if [ is-loaded PrgEnv-gnu ] {
  } else {
    module swap PrgEnv-cray PrgEnv-gnu
    setenv PE_PRODUCT_LIST [join [lsearch -all -inline -not -exact [split $::env(PE_PRODUCT_LIST) ":"] "CRAY"]]
    module unload cray-shmem
    module unload cce
    module unload intel
    module swap gcc gcc/4.8.1
    module swap craype craype/1.06
    module swap cray-mpich cray-mpich/6.0.2
    module load git/1.8.1.4
    module load cmake/2.8.10.2
  }
