  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    setenv PE_PRODUCT_LIST [join [lsearch -all -inline -not -exact [split $::env(PE_PRODUCT_LIST) ":"] "CRAY"]]
    module unload cray-shmem
    module unload cce
    module unload intel
    module swap gcc gcc/4.8.2
    module swap craype craype/2.04
    module swap cray-mpich cray-mpich/6.2.1
    module swap cray-libsci cray-libsci/12.1.3
    module load git/1.8.1.4
    module load cmake/2.8.10.2
    module load craype-target-native
  }

  setenv CRAYPE_LINK_TYPE dynamic
