  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module swap craype craype/2.1.0
    module unload cray-shmem
    module unload cray-mpich
    module unload atp
    module unload cray-libsci
    module unload craype-network-aries
    module load craype-network-none
    module swap gcc gcc/4.8.2
    module load git/1.8.1.4
    module load cmake/2.8.10.2
  }

  setenv CRAYPE_LINK_TYPE dynamic
