  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module unload cray-shmem
    module swap gcc gcc/4.8.2
    module swap craype craype/2.04
    module swap cray-mpich cray-mpich/6.2.1
    module load cray-libsci/12.1.3
    module load git/1.8.1.4
    module load cmake/2.8.10.2
  }

  setenv CRAYPE_LINK_TYPE static
