  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module swap gcc gcc/4.9.0
    module swap craype craype/2.1.3
    module swap cray-mpich cray-mpich/7.0.1
    module load cray-libsci/13.0.0
    module load git/1.8.1.4
    module load cmake/2.8.10.2
  }

  setenv CRAYPE_LINK_TYPE dynamic
