  if [ is-loaded PrgEnv-gnu ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-gnu
    }
    if [ is-loaded PrgEnv-intel ] {
      module swap PrgEnv-intel PrgEnv-gnu
    }
    module swap gcc gcc/5.3.0
    module swap craype craype/2.5.4
    module swap cray-mpich cray-mpich/7.3.3
    module load cray-libsci/16.03.1
    module load git/2.1.0
    module load cmake/3.2.3
    module swap craype-haswell craype-sandybridge
  }

  setenv CRAYPE_LINK_TYPE dynamic
