
# System configuration

include ../../system/$(TARGET).make
include ../../system/defaults.make

# Package parameters

PKG_NAME = cfitsio

PKG_VERSION = 3.30

PKG_COMPRESSED = cfitsio3300.tar.gz

PKG_UNCOMPRESSED = cfitsio

PKG_BUILDDIR = $(PKG_UNCOMPRESSED)

PKG_XTAR = $(GXTAR)

PKG_PATCHES =


# rules for this package

pre-fetch :

configure :

pre-install :

clean :


# Include common package rules

include ../pkg.make

